In [1]:
import numpy as np
from numpy.linalg import inv
import matplotlib.pyplot as plt
import random

In [4]:
path = '/Users/reneehlozek/Code/CIFAR_Network/GIMME/GIMME_analyses/CleanedGIMMEData/Control_group_output/individual/'
data = np.loadtxt(path+'1001Betas.csv', skiprows=1, usecols=range(1,9), delimiter=',')
B = data[:,:4] 
A = data[:,4:]

In [5]:
A

array([[0.    , 0.2215, 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    ]])

In [6]:
B

array([[0.    , 0.    , 0.    , 0.2504],
       [0.    , 0.3528, 0.    , 0.    ],
       [0.    , 0.    , 0.319 , 0.227 ],
       [0.    , 0.    , 0.    , 0.    ]])

In [7]:
#Testing Y = [BY'+C][I-A]^-1 for individual 1
A = np.zeros((4,4))
A[1,2] = 0.2215
B = np.zeros((4,4))
B[1,0], B[2,2], B[3,0], B[3,3] = 0.2504, 0.3528, 0.227, 0.319 
C = np.array([[np.sqrt(0.01)*np.random.randn()],
              [np.sqrt(0.01)*np.random.randn()],
              [np.sqrt(0.01)*np.random.randn()],
              [np.sqrt(0.01)*np.random.randn()]])
Y_lagged = np.ones((4,1))
Y = np.dot((np.transpose(np.dot(B, Y_lagged)+C)),np.identity(4)-A)
Y #vr,ss,anx,int

array([[0.05923972, 0.28876457, 0.12909153, 0.53625699]])

In [ ]:
#load beta values from csv file 
#construct A, B matrices
#initialize M = 76x4 zeroes matrix 
#for row in M: 
    #M[row] = lagged variables 
    #Compute Y
    #M[row+1] = Y

In [9]:
#load beta values from gimme output files and construct matrices A and B

numbers = ['01','02','03','04','05','06','07','08','09','10','11','12','13']
path = '/Users/reneehlozek/Code/CIFAR_Network/GIMME/GIMME_analyses/CleanedGIMMEData/Control_group_output/individual/'
for num in numbers:
    data = np.loadtxt(path+'10'+num+'Betas.csv', skiprows=1, usecols=range(1,9), delimiter=',')
    A = data[:,4:] #same day beta values
    B = data[:,:4] #lagged beta values
    
    M = np.zeros((76,4)) #store data into M 
    M[0] = np.ones((1,4)) #day 1 data same for all
    
    var_vr, var_ss, var_anx, var_int = 0.01, 0.01, 0.01, 0.01        
    times=np.arange(0,76)
    t = times[0:-1] #[0,...,74]
    
    for day in t: #updating each row in M
        
        C = np.array([[np.sqrt(var_vr)*np.random.randn()],
                      [np.sqrt(var_ss)*np.random.randn()],
                      [np.sqrt(var_anx)*np.random.randn()],
                      [np.sqrt(var_int)*np.random.randn()]])
        
        Y_lagged = np.reshape(M[day], (4,1)) #same day vr,ss,anx,int
        Y = np.dot((np.transpose(np.dot(B, Y_lagged)+C)),np.identity(4)-A) #next day vr,ss,anx,int
        M[day+1] = Y 
    
    np.savetxt('individual 10'+num, M[1:], delimiter=',', header='VR,SS,ANX,INT')

In [20]:
import random
randomlist = random.sample(range(1, 22), 5)
randomlist

[17, 8, 4, 2, 10]